Traceback (most recent call last):
  File "C:\Users\mirjam\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mirjam\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\mirjam\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# This cell should have its output hidden!
for book in root.findall('book'):
    title = book.find('title').text
    print(title)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# This cell should have its output hidden![39;00m
[1;32m----> 2[0m [38;5;28;01mfor[39;00m book [38;5;129;01min[39;00m [43mroot[49m[38;5;241m.[39mfindall([38;5;124m'[39m[38;5;124mbook[39m[38;5;124m'[39m):
[0;32m      3[0m     title [38;5;241m=[39m book[38;5;241m.[39mfind([38;5;124m'[39m[38;5;124mtitle[39m[38;5;124m'[39m)[38;5;241m.[39mtext
[0;32m      4[0m     [38;5;28mprint[39m(title)

[1;31mNameError[0m: name 'root' is not defined
NameError: name 'root' is not defined

